"""empty message

Revision ID: 53b3216c5942
Revises: a8a203c7c59b
Create Date: 2021-07-22 14:58:51.007228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b3216c5942'
down_revision = 'a8a203c7c59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('booking_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'booking_type')
    # ### end Alembic commands ###
